{% set name = "snyk-ls" %}
{% set version = "20250806.140213" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snyk/snyk-ls/archive/v{{ version }}.tar.gz
  sha256: 28018b69e4d06dbf9bf7e8f836efde44dd256b4e3bc92a7bcf9915cf6109d3ab

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - snyk-ls &  # [unix]
    - exe_pid=$!  # [unix]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [unix]
    - start /b snyk-ls   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im snyk-ls.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/snyk/snyk-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language Server used by IDEs as Snyk Backend for Frontends
  dev_url: https://github.com/snyk/snyk-ls

extra:
  recipe-maintainers:
    - danielnachun
