{% set name = "snyk-ls" %}
{% set version = "20251219.161916" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snyk/snyk-ls/archive/v{{ version }}.tar.gz
  sha256: 9f1c3a01a71e615f062beea8137c345b185461ef9cd8c9ed5fd153aa90d1ee22

build:
  number: 0
  skip: true  # [ppc64le]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - snyk-ls &  # [unix]
    - exe_pid=$!  # [unix]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [unix]
    - start /b snyk-ls   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im snyk-ls.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/snyk/snyk-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language Server used by IDEs as Snyk Backend for Frontends
  dev_url: https://github.com/snyk/snyk-ls

extra:
  recipe-maintainers:
    - danielnachun
