{% set name = "snyk-ls" %}
{% set version = "20240830.154625" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snyk/snyk-ls/archive/v{{ version }}.tar.gz
  sha256: 5caa5ba8009b691e013d461af876845d0c554de67751ec97b39b82ac120f8b44

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - snyk-ls --help 2>&1 | grep -q "Usage of snyk-ls"

about:
  home: https://github.com/snyk/snyk-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language Server used by IDEs as Snyk Backend for Frontends
  dev_url: https://github.com/snyk/snyk-ls

extra:
  recipe-maintainers:
    - danielnachun
