{% set name = "snyk-ls" %}
{% set version = "20241113.130608" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snyk/snyk-ls/archive/v{{ version }}.tar.gz
  sha256: 6b9f432ed7f387b3b75b6174fe6b299ff6aac87cd3ba844b0297d199a646d785

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - snyk-ls &  # [unix]
    - exe_pid=$!  # [unix]
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM  # [unix]
    - start /b snyk-ls   # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]
    - taskkill /F /im snyk-ls.exe  # [win]
    - if %errorlevel% neq 0 exit %errorlevel%  # [win]

about:
  home: https://github.com/snyk/snyk-ls
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language Server used by IDEs as Snyk Backend for Frontends
  dev_url: https://github.com/snyk/snyk-ls

extra:
  recipe-maintainers:
    - danielnachun
